[tool.poetry]
name = "projektikansio1"
version = "0.1.0"
description = "python juttuja"
authors = ["Miko <hakkarainenmiko@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"